package com.companerobot.enums;

public enum OrderStatus {
    WAITING_PICKUP_ADDRESS,
    WAITING_DESTINATION_ADDRESS,
    WAITING_IF_NOTES_NEEDED,
    WAITING_NOTES,
    WAITING_PRICE,
    WAITING_DEPARTURE_DETAILS,
    PASSENGER_CONFIRMATION_WAITING,
    DRIVER_WAITING,
    WAITING_DRIVER_LOCATION,
    DRIVER_ACCEPTED,
    DRIVER_ON_PICKUP,
    ORDER_FINISHED,
    ORDER_CANCELED,
    POSTPONED_CONVERSATION_RESULT_WAITING
}
